### ISSUE TITLE
phploc uses deprecated functionality

### ISSUE THREAD

**Issue by maikgreubel** [sebastianbergmann/phploc#101]
During execution in jenkins (great tutorial by the way) I get this message:

     [exec] Deprecated: DialogHelper is deprecated since version 2.5 and will be removed in 3.0. Use QuestionHelper instead. in /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 33
     [exec] 
     [exec] Call Stack:
     [exec]     0.0004     124648   1. {main}() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/phploc:0
     [exec]     0.0378     556820   2. SebastianBergmann\PHPLOC\CLI\Application->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/phploc:63
     [exec]     0.1091     566296   3. Symfony\Component\Console\Application->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/src/CLI/Application.php:67
     [exec]     0.1091     566404   4. Symfony\Component\Console\Application->getDefaultHelperSet() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Application.php:88
     [exec]     0.1148     668292   5. Symfony\Component\Console\Helper\DialogHelper->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Application.php:953
     [exec]     0.1148     668392   6. trigger_error() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php:33
     [exec] 
     [exec] 
     [exec] Fatal error: Cannot call constructor in /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Helper/DialogHelper.php on line 35
     [exec] 
     [exec] Call Stack:
     [exec]     0.0004     124648   1. {main}() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/phploc:0
     [exec]     0.0378     556820   2. SebastianBergmann\PHPLOC\CLI\Application->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/phploc:63
     [exec]     0.1091     566296   3. Symfony\Component\Console\Application->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/phploc/phploc/src/CLI/Application.php:67
     [exec]     0.1091     566404   4. Symfony\Component\Console\Application->getDefaultHelperSet() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Application.php:88
     [exec]     0.1148     668292   5. Symfony\Component\Console\Helper\DialogHelper->__construct() /var/lib/jenkins/jobs/phpGenerics/workspace/vendor/symfony/console/Symfony/Component/Console/Application.php:953

In my composer.json I defined version 2.0.6 for require-dev. phploc should use either a fixed version of symfony/console or be updated and not using the deprecated functionality.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this. How do you trigger this? What are your commandline options passed to phploc?

**Comment by GrahamCampbell** [comment]
@sebastianbergmann Install through composer with minimum stability set to dev so that you load symfony 2.7.x-dev components.

**Comment by sebastianbergmann** [comment]
Thank you, @GrahamCampbell.

I only get a deprecation message when using `--git` together with `--progress`:

    PHP Deprecated:  "Symfony\Component\Console\Helper\ProgressHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\ProgressBar" instead. in /usr/local/src/phploc/vendor/symfony/console/Symfony/Component/Console/Helper/HelperSet.php on line 84

This message is different from the one posted by @maikgreubel, though.
