### ISSUE TITLE
PHPLOC classifies empty line at the end of a document as a line of code

### ISSUE THREAD

**Issue by mostwanted1976** [sebastianbergmann/phploc#103]
PHPLOC classifies an empty line at the end of a document as a line of code. AFAIK it is best practice to have a line break (an empty line) at the end of every document to play safe with source code version control systems. i think it would be more appropriate to not count those trailing empty lines as a line of code. what do you think.

**Comment by sebastianbergmann** [comment]
Every line, including blank lines, is a line of code.
