### ISSUE TITLE
test class and method count not working

### ISSUE THREAD

**Issue by FunTimeCoding** [sebastianbergmann/phploc#105]
`phploc --count-tests src test`

prints

```
Tests
  Classes                                            0
  Methods                                            0
```

even though `test/Example/CalculatorTest.php` contains

```php
<?php
namespace Example;

use Exception;
use PHPUnit_Framework_TestCase;

class CalculatorTest extends PHPUnit_Framework_Testcase
{
    public function testAddPositiveNumbers()
    {
        $calc = new Calculator();
        $result = $calc->add(1, 2);
        $this->assertEquals(3, $result);
    }
}
```

**Comment by FunTimeCoding** [comment]
bump

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:

    $ phploc --count-tests src tests
    phploc 2.0.6 by Sebastian Bergmann.

    Directories                                          4
    Files                                              194

    Size
      Lines of Code (LOC)                            14055
      Comment Lines of Code (CLOC)                   10215 (72.68%)
      Non-Comment Lines of Code (NCLOC)               3840 (27.32%)
      Logical Lines of Code (LLOC)                     577 (4.11%)
        Classes                                        264 (45.75%)
          Average Class Length                           1
          Average Method Length                          1
        Functions                                      120 (20.80%)
          Average Function Length                      120
        Not in classes or functions                    193 (33.45%)

    Complexity
      Cyclomatic Complexity / LLOC                    0.04
      Cyclomatic Complexity / Number of Methods       1.09

    Dependencies
      Global Accesses                                    0
        Global Constants                                 0 (0.00%)
        Global Variables                                 0 (0.00%)
        Super-Global Variables                           0 (0.00%)
      Attribute Accesses                                35
        Non-Static                                      27 (77.14%)
        Static                                           8 (22.86%)
      Method Calls                                     332
        Non-Static                                     146 (43.98%)
        Static                                         186 (56.02%)

    Structure
      Namespaces                                         1
      Interfaces                                         3
      Traits                                             0
      Classes                                          187
        Abstract Classes                                 0 (0.00%)
        Concrete Classes                               187 (100.00%)
      Methods                                          217
        Scope
          Non-Static Methods                           214 (98.62%)
          Static Methods                                 3 (1.38%)
        Visibility
          Public Methods                               211 (97.24%)
          Non-Public Methods                             6 (2.76%)
      Functions                                          1
        Named Functions                                  0 (0.00%)
        Anonymous Functions                              1 (100.00%)
      Constants                                          0
        Global Constants                                 0 (0.00%)
        Class Constants                                  0 (0.00%)

    Tests
      Classes                                            3
      Methods                                           42

**Comment by FunTimeCoding** [comment]
is this the LOC from phploc itself?

**Comment by sebastianbergmann** [comment]
No, from https://github.com/sebastianbergmann/money/

**Comment by FunTimeCoding** [comment]
Actually never mind, I ran the test again and it works now. No idea why, but it fixed itself.

**Comment by FunTimeCoding** [comment]
I found out the actual problem.

PHPUnit_Framework_Testcase != PHPUnit_Framework_TestCase

PHP will allow extending from lower case c but phploc does not detect it. Does that make this a bug?

**Comment by GrahamCampbell** [comment]
No. While php class names are not case sensitive, some filesystems are, effectively making the class names case sensitive when it comes to autoloading.

**Comment by FunTimeCoding** [comment]
Alright.
