### ISSUE TITLE
phploc has no change log

### ISSUE THREAD

**Issue by ravage84** [sebastianbergmann/phploc#108]
I'm currently using phploc 2.0.6 and saw 2.1.0 was released.
Eager to know what's new I was looking for a change log or release notes.
Neither exist.
In the end I browsed through the commit messages between 2.1.0 <=> 2.0.6.
It would be more convenient for implementing developers if there was a change log of some sorts.

That's why I propopse to include one, like explained here:
http://keepachangelog.com/

**Comment by sebastianbergmann** [comment]
Yes, I know that not having a changelog is a bad thing. But if you already browsed through the commit messages then why did you not create a changelog and send a pull request for it?

**Comment by ravage84** [comment]
I normally would but my knowledge about phploc is very limited and picking only the relevant changes from a long list of commits isn't easy in that case.
Because including __everything__ (including minor stuff) into a change log isn't the solution.

But I will propose a change log we can build on.

**Comment by sebastianbergmann** [comment]
I recently did this (https://github.com/sebastianbergmann/phpunit/commit/2df5bbd4767ce2a4b0375fe2d58bbc27bed999e7) for PHPUnit. I plan on doing it for all PHPUnit-related components next and eventually for all of my projects. Any help with that would be appreciated. Thanks!

**Comment by ravage84** [comment]
Perfect, I also had http://keepachangelog.com/ in mind.
