### ISSUE TITLE
 Undefined index: lloc in Analyser.php

### ISSUE THREAD

**Issue by KacerCZ** [sebastianbergmann/phploc#110]
Hi,
I encountered following PHP notices using phploc 2.1.1 (installed via composer):

    phploc 2.1.1 by Sebastian Bergmann.

    PHP Notice:  Undefined index: lloc in vendor/phploc/phploc/src/Analyser.php on line 304
    PHP Stack trace:
    PHP   1. {main}() vendor/phploc/phploc/phploc:0
    PHP   2. Symfony\Component\Console\Application->run()     vendor/phploc/phploc/phploc:31
    PHP   3. SebastianBergmann\PHPLOC\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
    PHP   4. Symfony\Component\Console\Application->doRun() vendor/phploc/phploc/src/CLI/Application.php:102
    PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
    PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
    PHP   7. SebastianBergmann\PHPLOC\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    PHP   8. SebastianBergmann\PHPLOC\CLI\Command->executeSingle() vendor/phploc/phploc/src/CLI/Command.php:113
    PHP   9. SebastianBergmann\PHPLOC\CLI\Command->count() vendor/phploc/phploc/src/CLI/Command.php:133
    PHP  10. SebastianBergmann\PHPLOC\Analyser->countFiles() vendor/phploc/phploc/src/CLI/Command.php:237
    PHP  11. SebastianBergmann\PHPLOC\Analyser->countFile() vendor/phploc/phploc/src/Analyser.php:159
    PHP Notice:  Undefined index: ccn in vendor/phploc/phploc/src/Analyser.php on line 499
    PHP Stack trace:
    PHP   1. {main}() vendor/phploc/phploc/phploc:0
    PHP   2. Symfony\Component\Console\Application->run() vendor/phploc/phploc/phploc:31
    PHP   3. SebastianBergmann\PHPLOC\CLI\Application->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
    PHP   4. Symfony\Component\Console\Application->doRun() vendor/phploc/phploc/src/CLI/Application.php:102
    PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Symfony/Component/Console/Application.php:195
    PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Symfony/Component/Console/Application.php:874
    PHP   7. SebastianBergmann\PHPLOC\CLI\Command->execute() vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    PHP   8. SebastianBergmann\PHPLOC\CLI\Command->executeSingle() vendor/phploc/phploc/src/CLI/Command.php:113
    PHP   9. SebastianBergmann\PHPLOC\CLI\Command->count() vendor/phploc/phploc/src/CLI/Command.php:133
    PHP  10. SebastianBergmann\PHPLOC\Analyser->countFiles() vendor/phploc/phploc/src/CLI/Command.php:237
    PHP  11. SebastianBergmann\PHPLOC\Analyser->countFile() vendor/phploc/phploc/src/Analyser.php:159

PHP Version

    PHP 5.6.7-1+deb.sury.org~utopic+1 (cli) (built: Mar 24 2015 11:23:10) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
        with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

I was able to isolate problematic file and reduce its content to small sample still causing both notices:

    <?php
    class LocTest {
        public function & __get( $name ) {
                $value = NULL;
                if ( $this->hasProperty( $name ) )
                {
                        $value = $this->$name;
                }
                return $value;
        }
    }

**Comment by sebastianbergmann** [comment]
Interesting whitespace you have there: replacing `function & __get` with `function &__get` makes the error go away. Thanks for the reproducing test case!
