### ISSUE TITLE
Average-metrics missing in xml/csv result

### ISSUE THREAD

**Issue by SchulteMarkus** [sebastianbergmann/phploc#111]
It seems as if at least some "average" metrics are missing in phploc xml- or csv-result.

I am using phploc 2.1.1. I pasted [console-output](http://pastebin.com/zXYukEJq),  [xml-output](http://pastebin.com/rSEu9DF6) and [csv-output](http://pastebin.com/kQ3aZkaT) on pastebin.

As far as I can see
- "Average Function Length" (from console) is missing in xml output. 
- "Average Class Length" and "Average Method Length" (from console) is missing in csv output. 
- "Average Complexity per LLOC", "Average Complexity per Class" and "Average Complexity per Method" seem to be missing both in xml- and csv-output.

**Comment by ghorvath** [comment]
This is biting me now -- can this PR be merged soon?

**Comment by sebastianbergmann** [comment]
@ghorvath Does #118 solve the problem?

**Comment by ghorvath** [comment]
Yes -- that will do it. It was exactly those average metrics that I was looking for.

**Comment by sebastianbergmann** [comment]
Does the problem persist in `master`?

**Comment by dehrk** [comment]
Average Class Length (LLOC) & Average Method Length (LLOC) are still missing from the CSV in phploc 3.0.1

**Comment by reinholdfuereder** [comment]
Update "only" ad CSV in 4.0.1:
- Still exactly as mentioned by @dehrk for 3.0.1: 
  - > Average Class Length (LLOC) & Average Method Length (LLOC) are still missing
- Not exactly anymore as mentioned by @SchulteMarkus in the original issue/comment for 2.1.1:
  - > "Average Complexity per LLOC", "Average Complexity per Class" and "Average Complexity per Method" seem to be missing both in xml- and csv-output.
  - Only "Average Complexity per Class" is still missing (but "Average Complexity per LLOC" and "Average Complexity per Method" are already there/available)

**Comment by reinholdfuereder** [comment]
Update "only" ad XML in 4.0.1:
- As expected -- when looking at the source code of https://github.com/sebastianbergmann/phploc/blob/master/src/Log/Xml.php -- all metrics are now already part of the XML (as it iterates over all available entries in the array; the percentage-"type" metrics are not in XML, but are based on metrics in XML and could be calculated according to https://github.com/sebastianbergmann/phploc/blob/master/src/Log/Text.php)

**Comment by reinholdfuereder** [comment]
@sebastianbergmann I could also add all other missing metrics to the little patch PR #177 (and therefore rename/re-title it)? So not just the most important average metrics, but all from XML, but not yet in CSV.

These metrics are now (v4.0.1) in XML, but not in CSV:
- ccn: this is also missing in Text output; if this should be included, what could be a nice description? maybe overall sum of cyclomatic complexity?
- ccnMethods: this is also missing in Text output; if this should be included, what could be a nice description? maybe overall sum of cyclomatic complexity in/of methods?
- classCcnMax: Maximum Class Complexity
- classCcnMin: Minimum Class Complexity
- classLlocMax: Maximum Class Length (LLOC)
- classLlocMin: Minimum Class Length (LLOC)
- methodCcnMax: Maximum Method Complexity
- methodCcnMin: Minimum Method Complexity
- methodLlocMax: Maximum Method Length (LLOC)
- methodLlocMin: Minimum Method Length (LLOC)

**Comment by reinholdfuereder** [comment]
I think thanks to the recent merge of PR #177 by @sebastianbergmann this issue's original requirements are IMHO solved (cf. https://github.com/sebastianbergmann/phploc/issues/111#issuecomment-357988240 and https://github.com/sebastianbergmann/phploc/issues/111#issuecomment-358010614) and this issue could be marked as resolved/fixed.

(Also because https://github.com/sebastianbergmann/phploc/issues/111#issuecomment-358248549 is a different "story", i.e. should/could be another dedicated issue, if required...)
