### ISSUE TITLE
PHP  Undefined indexes when running ci

### ISSUE THREAD

**Issue by pfwd** [sebastianbergmann/phploc#112]
phploc-ci:
     [exec] phploc 2.1.1 by Sebastian Bergmann.

PHP Notice:  Undefined index: lloc in 
~/.composer/vendor/phploc/phploc/src/Analyser.php on line 304

PHP Notice:  Undefined index: ccn in 
~/.composer/vendor/phploc/phploc/src/Analyser.php on line 315

**Comment by kdambekalns** [comment]
Just wanted to report the same… :)

**Comment by Nikoms** [comment]
Same here: https://github.com/sebastianbergmann/phploc/issues/110

**Comment by sebastianbergmann** [comment]
Does the problem still exist in phploc 2.1.2?

**Comment by Nikoms** [comment]
I tried with the 2.1.2 and I have the same notice:

[phploc] phploc 2.1.2 by Sebastian Bergmann.
[phploc] 
[phploc] PHP Notice:  Undefined index: lloc in /var/lib/jenkins/jobs/Project/workspace/vendor/phploc/phploc/src/Analyser.php on line 304

**Comment by sebastianbergmann** [comment]
Without code to reproduce this with there is not much I can do.

**Comment by moffe42** [comment]
Get the same error.

The following makes it fail

```
<?php

$container['test.key'] = function() {
    echo 'Test';
};
``` 

Run with 

phploc 2.1.3 by Sebastian Bergmann.

**Comment by afoeder** [comment]
Dear readers, see #142 for a follow-up since it's still there.
