### ISSUE TITLE
[PHP 5.3.3] PHP Parse error:  syntax error, unexpected '[', expecting ')' in phar:///usr/local/bin/phploc/src/CLI/Application.php on line 99

### ISSUE THREAD

**Issue by rbairwell** [sebastianbergmann/phploc#116]
Error occurs in PHP loc 2.1.2.phar downloaded on 04th June 2015.

I suspect:
ArrayInput(['--help']);
is the issue in src/CLI/Application.php as the square bracket array method is new to PHP 5.4 and the code environment I wanted a LOC on (to push for an upgrade) is stuck on PHP 5.3.3.

Any chance you can either make it backwards compatible with PHP 5.3 or at least add in a check early on for a minimum PHP version?

**Comment by sebastianbergmann** [comment]
TL;DR: I will not make PHPLOC compatible with PHP 5.3.

Active support for PHP 5.4 ended on September 14, 2014 and active support for PHP 5.5 will end on June 20, 2015. The active support for PHP 5.3 already ended on July 11, 2013.

**Comment by rbairwell** [comment]
I suspected that was going to be the answer and totally understand ;). I'm trying to push for the stack this client is using to come up to date but it's a hard slog.

Any chance of making the minimum PHP requirements clear on the Github page or in the code?

**Comment by sebastianbergmann** [comment]
The bump in the required version of PHP should not have happened in a minor release. I have released phploc 2.1.3, which is compatible again with PHP 5.3, to address this issue.

`master` is now `3.0-dev` and will only be supported on PHP >= 5.6.

**Comment by cassianotartari** [comment]
```
$ ./tools/phploc --version
phploc 7.0.1 by Sebastian Bergmann.
PHP Parse error:  syntax error, unexpected ')' in phar:///var/www/.phive/phars/phploc-7.0.1.phar/src/CLI/ArgumentsBuilder.php on line 117

Parse error: syntax error, unexpected ')' in phar:///var/www/.phive/phars/phploc-7.0.1.phar/src/CLI/ArgumentsBuilder.php on line 117
```
```
$ php -v
PHP 7.2.33 (cli) (built: Sep  1 2020 05:42:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by sebastianbergmann** [comment]
PHP 7.2 is no longer supported.
