### ISSUE TITLE
Output of phploc

### ISSUE THREAD

**Issue by HieronyM** [sebastianbergmann/phploc#123]
Dear Sebastian,

I am using phploc 2.0.5, 
and for the output, I use .csv file using this command.

```groovy
executable "$vendorDir/phploc.bat"
args "--log-csv", "build/logs/phploc.csv", "src"
```

It redirect the output to .csv file, but the csv file contents is so mess.
Can you help me to make the .csv file more readable.

This is the contents of the file.
![csv_file_problem](https://cloud.githubusercontent.com/assets/8222055/9032313/749962e6-39e7-11e5-83d7-4f04dfb1e67a.png)

Thanks for your Help.
:D

**Comment by Eternal-Infinity** [comment]
As far as I can see the .csv-file seems pretty fine.
If you want to have some fancy visual effects or something, you could integrate phploc into a CI-System like Jenkins.
Or you can check the output on the CLI, there the output is way more readable than in the .csv

**Comment by HieronyM** [comment]
Dear Eternal-Infinity,
My Fault, My mentor said that too..

Hahahhaha.
I think the csv file is mess..
Sorry Sebastian.
:D
