### ISSUE TITLE
Lower console dependency

### ISSUE THREAD

**Issue by sagikazarmark** [sebastianbergmann/phploc#128]
The project currently requires 2.5 or higher version of symfony console. Is it possible to make it ~2.3?

**Comment by sebastianbergmann** [comment]
A tool such as PHPLOC should not be installed via Composer anyway and instead be used using a PHAR. If you want to use it via Composer you can ... unless its dependencies conflict with your own. This potential for conflict is the reason I suggest using the PHAR.
