### ISSUE TITLE
Undefined index: lloc

### ISSUE THREAD

**Issue by leonardor** [sebastianbergmann/phploc#137]
[phploc] phploc 2.1.5 by Sebastian Bergmann.
   [phploc]
   [phploc] PHP Notice:  Undefined index: lloc in phar:///phploc.phar/src/Analyser.php on line 312

**Comment by sebastianbergmann** [comment]
Can you check whether the problem still exists in current `master`?

**Comment by sebastianbergmann** [comment]
Duplicate of #125.
