### ISSUE TITLE
Log results in JSON format

### ISSUE THREAD

**Issue by samayo** [sebastianbergmann/phploc#149]
Sorry if this feature already exists, but I've looked and so far found nothing. So, my question is, is it possible to get the results from phploc in JSON format?

**Comment by sebastianbergmann** [comment]
I am not interested in JSON.

**Comment by kelunik** [comment]
@sebastianbergmann Just leave it open and wait for a PR?

**Comment by J7mbo** [comment]
@sebastianbergmann Hardly the nicest response...

**Comment by sebastianbergmann** [comment]
It was not my intention to be "not nice".

I do not see how a JSON logfile would be useful. I am neither going to implement support for JSON logfiles nor am I interested in merging a pull request that implements it. This is why I closed the pull request.

**Comment by kelunik** [comment]
It's as useful as the XML log, right?

**Comment by sebastianbergmann** [comment]
After discussing this over at https://chat.stackoverflow.com/transcript/message/37489922#37489922, let me say this: I will merge a pull request that implements this.

I still prefer XML over JSON, but who am I to force people to use XML.
