### ISSUE TITLE
'LC_ALL' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by edsonmedina** [sebastianbergmann/phploc#152]
I got this output when running phploc on git-bash on windows:

```
$/vendor/phploc/phploc/phploc --log-csv log.csv --progress --git-repository . .
phploc 3.0.1 by Sebastian Bergmann.

'LC_ALL' is not recognized as an internal or external command,
operable program or batch file.


  [SebastianBergmann\Git\RuntimeException]


phploc [--names NAMES] [--names-exclude NAMES-EXCLUDE] [--count-tests] [--git-repository GIT-REPOSITORY] [--exclude EXCLUDE] [--log-csv LOG-CSV] [--log-xml LOG-XML] [--progress] [--] [<values>]...

```

Is there anything I'm doing wrong?

**Comment by sebastianbergmann** [comment]
Looks related to either https://github.com/sebastianbergmann/git/commit/7ae71cc006f7c5081f3c2ee61d4953143b8ffa9f or https://github.com/sebastianbergmann/git/commit/38638de3e94830a5cd7a5956135589b967609cd5.

@remicollet Can you have a look?

**Comment by remicollet** [comment]
@sebastianbergmann I think we have to remove the inline env setting.

What you you prefer ?
- switch back to the previous version using getenv/putenv ?
- add it only on non-windows env ?

**Comment by sebastianbergmann** [comment]
Add it only on non-windows, I guess.

**Comment by sebastianbergmann** [comment]
Should be fixed by https://github.com/sebastianbergmann/git/pull/26

**Comment by edsonmedina** [comment]
Thank you!
