### ISSUE TITLE
An error under php 7

### ISSUE THREAD

**Issue by SilentTiger** [sebastianbergmann/phploc#155]
I got the error like this:
[root@TIger-centos-VM workflow]# phploc /var/lib/jenkins/workspace/workflow/
phploc 3.0.1 by Sebastian Bergmann.

PHP Notice:  Undefined index: ccn in phar:///usr/local/bin/phploc/src/Analyser.php on line 317
Directories                                        212
Files                                             1219

My environment:
[root@TIger-centos-VM workflow]# php -v
PHP 7.0.9 (cli) (built: Aug 15 2016 14:02:36) ( NTS )

CentOS 6.5 64bit

**Comment by callistino** [comment]
I got this same error and in my case it was happening while using an the [anonymous class](http://php.net/manual/en/language.oop5.anonymous.php) feature in php7. I had to refactor it to a regular named class.

**Comment by kelunik** [comment]
`dev-master` seems to fix it for `amphp/aerys`. @sebastianbergmann Could you release a new bugfix version?

**Comment by josephzidell** [comment]
I am facing the same issue

**Comment by sebastianbergmann** [comment]
Please open a new ticket in case this problem still exists in PHPLOC 4.
