### ISSUE TITLE
Count only a bunch of folders or exclude some folder.

### ISSUE THREAD

**Issue by StanBarrows** [sebastianbergmann/phploc#156]
Hey together, 

I'm working currently on a Laravel Project and would like to count my lines of code. I've already installed the **phploc** library and it's working almost perfect. I just struggle with excluding more than one folder or just count a specific folder structure.

I would like to **Exclude:**
- ./vendor
- ./storage 
- ./ressources/assets
- ./public
- ./node_modules 
- ./bootstrap
- ./app/Console

I've already tried something like the following example but always get an unrealistic code back. **(  Lines of Code (LOC)                          3'112'657)**    I found another Mac Programm that counts just the specific lines from .php files in folders and I got back something like 6000 lines of code. This would be more realistic but i don't have the further information the phploc provides.

**First Try:**
`vendor/bin/phploc --exclude ./vendor . --exclude ./storage . --exclude ./node_modules . --exclude ./bootstrap . --exclude ./app/Console . --exclude ./storage . --exclude ./resources/assets .`

**Second Try:**
`./vendor . ./storage .  ./ressources/assets . ./public . ./node_modules . ./bootstrap . ./app/Console .`

I would like to count only the structure as you can see it on the attached image. Do you may have any suggestions? 

Best regards
Sebastian

![phploc](https://cloud.githubusercontent.com/assets/10268813/19214974/b6e99268-8d99-11e6-8e7a-ffec2d9c7402.png)

**Comment by zdenekdrahos** [comment]
```
vendor/bin/phploc ./ --exclude bootstrap --exclude node_modules \
  --exclude public --exclude storage --exclude vendor
```

Alternatively you can try [phpqa](https://github.com/EdgedesignCZ/phpqa#analyze). It simplifies ignoring directories in various QA tools:

```
phpqa --analyzedDir ./  --ignoredDirs=bootstrap,node_modules,public,storage,vendor \
  --tools phploc --output cli
```

**Comment by SebastianFix** [comment]
Hey zdenekdrahos, thank you for the message

Unfortunately your posted link always ends up with a "no such file in this directory" Do the folder names  have to be in alphabetical order?

![nsf](https://cloud.githubusercontent.com/assets/10268813/19220138/c0a950a0-8e2e-11e6-92f5-03948cd23a6c.png)

**Comment by zdenekdrahos** [comment]
It looks like `vendor/bin/phploc` does not exist. Are you executing the command in the root of project?
Folders can be in any order.

**Comment by SebastianFix** [comment]
Hey zdenekdrahos, thank you! yes that was the problem.

But i still cant trust the output. For this i tried to run an empty test. So exclude all avalable folders. Then i ran the test with add a folder step by step and counted the output.

So if you now count the blue containers you get something like 6000 LOC - what is realistic and i got confirmed from another program. But if you run the command just like you see in the red container i get an output with like 10000 LOC. So there seems to be an bug.

![strange](https://cloud.githubusercontent.com/assets/10268813/19221173/ab44cc36-8e46-11e6-9e5c-c03837865421.png)

![classes](https://cloud.githubusercontent.com/assets/10268813/19221196/1809482e-8e47-11e6-8c12-9468ebf97c46.png)

Anyhow, is it not possible to add Subfolders? 

Thanks for the link, i'll try to one out as well.

Cheers
Sebastian

**Comment by zdenekdrahos** [comment]
Good catch, excluding subfolders is tricky in [symfony/finder](https://github.com/sebastianbergmann/finder-facade/blob/master/src/FinderFacade.php#L84). Exclude is relative to analyzed directory:

```bash
$ vendor/bin/phploc src/ | grep NCLOC
  Non-Comment Lines of Code (NCLOC)                702 (94.10%)
$ vendor/bin/phploc src/ --exclude src/Task/ | grep NCLOC 
  Non-Comment Lines of Code (NCLOC)                702 (94.10%)
$ vendor/bin/phploc src/ --exclude Task | grep NCLOC 
  Non-Comment Lines of Code (NCLOC)                571 (95.17%)

# 702 - 571 = 131 ignored lines
```

```bash
$ vendor/bin/phploc ./ --exclude=vendor | grep NCLOC 
  Non-Comment Lines of Code (NCLOC)               1017 (95.05%)
$ vendor/bin/phploc ./ --exclude=vendor --exclude src/Task | grep NCLOC 
  Non-Comment Lines of Code (NCLOC)                886 (95.89%)
$ vendor/bin/phploc ./ --exclude=vendor --exclude Task | grep NCLOC 
  Non-Comment Lines of Code (NCLOC)                886 (95.89%)

# 1017 - 886 = 131 ignored lies
```
