### ISSUE TITLE
"declare", "namespace", and "use" are not handled correctly

### ISSUE THREAD

**Issue by JeroenDeDauw** [sebastianbergmann/phploc#161]
"LLOC not in classes or functions" is including these things:

* `declare( strict_types = 1 );`
* namespace declaration
* import statements

When phploc reported 2000+ LLOC under "not in classes or functions" I was somewhat WTF. Strictly speaking it is not wrong I suppose, though it is making the distinction in a way that I unsuspected to me, and makes the metric kinda useless.

**Comment by petrkotek** [comment]
:+1: Yep, i just nocticed the very same thing. Would be nice to get this fixed.

**Comment by JeroenDeDauw** [comment]
I think this would still be a valuable feature to have. Without it, the "LLOC not in classes or functions" metric is useless to anyone with a modern PHP codebase.

**Comment by Tobion** [comment]
I was also irritated by this. Could this issue be reopened please?

**Comment by JeroenDeDauw** [comment]
@sebastianbergmann

**Comment by JeroenDeDauw** [comment]
#activity

**Comment by sebastianbergmann** [comment]
I would appreciate a pull request that fixes this a lot more than comments that prevent this ticket from going stale. I do not care enough about this to fix it myself, sorry.

**Comment by JeroenDeDauw** [comment]
Fair enough for not spending time on fixing this, though personally I find it odd that a ticket about a feature being broken gets closed just because there is little maintenance effort put into this tool.
