### ISSUE TITLE
Composer Warning: Package sebastian/git is abandoned

### ISSUE THREAD

**Issue by MarcusSchwarz** [sebastianbergmann/phploc#164]
```
Package sebastian/git is abandoned, you should avoid using it. No replacement was suggested.
$ composer why sebastian/git
phploc/phploc  3.0.1  requires  sebastian/git (~2.1)  
```

I see that the dependency has already been removed in the master, but not yet in the most recent release version.
When are you planning to push a new release of phploc?

**Comment by sebastianbergmann** [comment]
I do not understand the point of this issue. Version 3.0.1 of this component has a feature that uses `sebastian/git`. Just because `sebastian/git` is no longer maintained does not mean that it no longer works. I have no immediate plans for new releases of PHPLOC.
