### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by garak** [sebastianbergmann/phploc#165]
Last tag is over a year old and still depends on abandoned packages.
Could you please release a new tag?

**Comment by sebastianbergmann** [comment]
I would love to do so but it may not be as easy as you might assume. I do not know right now what the state of `master` is since there have been quite a few changes. I'll try to look into this ASAP.

**Comment by TomasVotruba** [comment]
Thank you @sebastianbergmann for such a fast action response!
