### ISSUE TITLE
Undefined index Analyser.php on line 507

### ISSUE THREAD

**Issue by Cotsios26** [sebastianbergmann/phploc#181]
I get this when i run a simple count

PHP Notice:  Undefined index: ccn in /usr/share/php/SebastianBergmann/PHPLOC/Analyser.php on line 507
PHP Notice:  Undefined index: ccn in /usr/share/php/SebastianBergmann/PHPLOC/Analyser.php on line 507

Please note that i have installed phploc using
apt install phploc

**Comment by sebastianbergmann** [comment]
Please do not report bugs for distribution/vendor-packaged versions. At least provide a version number.

**Comment by Cotsios26** [comment]
Sure. 
Yeah missed that.  Version number is (3.0.0-1build1).

**Comment by sebastianbergmann** [comment]
Please open a new ticket in case this problem still exists in a recent version of PHPLOC.
