### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by natzar** [sebastianbergmann/phploc#192]
After, wget, I try to run php phploc.phar

This is the result:
Parse error: parse error, expecting `';'' or `'{'' in phar:///Users/beto/phpQuality/phploc.phar/src/CLI/Application.php on line 101

**Comment by sebastianbergmann** [comment]
Which version of PHP do you use?

**Comment by natzar** [comment]
PHP 5.6.24 (cli) (built: Aug  8 2016 16:58:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by sebastianbergmann** [comment]
[PHP 5.6 is dead](https://thephp.cc/news/2016/12/php-5-active-support-ends-now-what) and not supported anymore (by PHPLOC and other software of mine).

**Comment by natzar** [comment]
Thanks!
