### ISSUE TITLE
Problem phploc, phpcpd and finder-facade

### ISSUE THREAD

**Issue by pyvm** [sebastianbergmann/phploc#202]
Hi ,
Its impossible to use `phpcpd` with `phploc` in the same pipeline because `phpcpd` need finder-face 2
but `phploc` want stability version of finder-face.
In php 7.3 with symfony 5

**Comment by sebastianbergmann** [comment]
IMHO, a tool such as PHPLOC should not be installed using Composer but rather be used from a PHAR.

Eventually, there will be new releases of PHPLOC etc. that will solve this issue for Composer-based usage. But this is not a priority for me right now.
