### ISSUE TITLE
Fatal error on phploc dev-master and PHPUnit 9

### ISSUE THREAD

**Issue by fijas** [sebastianbergmann/phploc#204]
>    [phploc] PHP Fatal error:  Uncaught TypeError: ini_set() expects parameter 2 to be string, int given in ..../vendor/phploc/phploc/src/CLI/Application.php:107
   [phploc] Stack trace:
   [phploc] #0 ..../vendor/phploc/phploc/src/CLI/Application.php(107): ini_set('xdebug.scream', 0)
   [phploc] #1 ..../vendor/phploc/phploc/src/CLI/Application.php(52): SebastianBergmann\PHPLOC\CLI\Application->disableXdebug()
   [phploc] #2 ..../vendor/symfony/console/Application.php(141): SebastianBergmann\PHPLOC\CLI\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
   [phploc] #3 ..../vendor/phploc/phploc/phploc(31): Symfony\Component\Console\Application->run()
   [phploc] #4 {main}
   [phploc]   thrown in ..../vendor/phploc/phploc/src/CLI/Application.php on line 107

Not sure if you are already aware of this and if it is a work in progress. But running `phploc` version `dev-master` is causing a fatal error. I had to use `dev-master` because `PHPUnit 9` and `phploc 5.0` were not getting installed together because of version constraint of `sebastian/version`. `PHP` version used is `7.3`.

**Comment by sebastianbergmann** [comment]
I do not recommend using Composer to install this tool anyway, simply use the PHAR in the meantime.

**Comment by garak** [comment]
I'm getting the same error on PHP 7.4 using phar downloaded from https://phar.phpunit.de/phploc.phar

**Comment by garak** [comment]
@sebastianbergmann do you mind to re-open this?
The phar is still not working
