### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by dereuromark** [sebastianbergmann/phploc#208]
The tool emits notices, probably some missing defensive coding somewhere

> PHP Notice:  Undefined offset: 7 in phar:///.../project/phploc.phar/src/Analyser.php on line 509

**Comment by sebastianbergmann** [comment]
Which version of PHPLOC do you use? Can you provide a minimal, self-contained piece of code that triggers the notice?

**Comment by dereuromark** [comment]
latest 6.0.2 downloaded today

**Comment by dereuromark** [comment]
It is hard to say what vendor file causes this, but I would just add a guard isset() clause in there to return early if the array key does not exist maybe.

**Comment by dereuromark** [comment]
while (\is_array($tokens[$i + 1]) && $tokens[$i + 1][0] !== \T_WHITESPACE) {

to 

    while (isset($tokens[$i + 1]) && \is_array($tokens[$i + 1]) && $tokens[$i + 1][0] !== \T_WHITESPACE) {

**Comment by sebastianbergmann** [comment]
Guarding the statement with an `isset()` does not actually solve the issue but instead just works around it. I want to understand why we run into a situation where that element does not exist. And for that I need a minimal, self-contained, reproducing test case.

**Comment by dereuromark** [comment]
I was able to trace it down to a specific vendor package
https://github.com/spryker/code-sniffer

**Comment by sebastianbergmann** [comment]
Sorry, but I need a single file.

**Comment by kubawerlos** [comment]
@dereuromark what is the version of `spryker/code-sniffer`? I've tried latest (`0.15.3`), `0.15.0`, `0.14.0` and `dev-master`, but no luck with reproduction the notice.

What is the PHP version you are using (should not matter, but how knows)? I've tested this on PHP 7.4.3.
