### ISSUE TITLE
Allows Symfony Console 5.0 when installing the version 5 on PHP 7.2

### ISSUE THREAD

**Issue by amandiobm** [sebastianbergmann/phploc#210]
I'm getting an error when installing on PHP 7.2.

```
- Installation request for phploc/phploc ^5.0 -> satisfiable by phploc/phploc[5.0.0].
- Conclusion: remove symfony/console v5.0.8
- Conclusion: don't install symfony/console v5.0.8
- phploc/phploc 5.0.0 requires symfony/console ^4.0
...
```

**Comment by amandiobm** [comment]
The fix seems pretty easy, I've cloned the repository, but I don't know how to proceed with PR

**Comment by sebastianbergmann** [comment]
[It is not recommended to use Composer to download and install this tool.](https://twitter.com/s_bergmann/status/999635212723212288)
