### ISSUE TITLE
Allow symfony/console ^5.0 in phploc 5.x

### ISSUE THREAD

**Issue by guvra** [sebastianbergmann/phploc#212]
Hi,

The version 5.x of this package doesn't allow the use of symfony/console ^5.0:

```json
        "symfony/console": "^4.0"
```

Expected requirements:

```json
        "symfony/console": "^4.0 || ^5.0"
```

Using phploc 6.x is not a valid workaround because it requires php 7.3.

**Comment by sebastianbergmann** [comment]
[It is not recommended to use Composer to download and install this tool.](https://twitter.com/s_bergmann/status/999635212723212288)
