### ISSUE TITLE
syntax error in ArgumentsBuilder

### ISSUE THREAD

**Issue by EtienneDelepine** [sebastianbergmann/phploc#220]
Hi, using phploc-7.0.1.phar I have this error 

Parse error: syntax error, unexpected ')' in phar://C:/Mes Documents C/DEV/phploc/phploc-7.0.1.phar/src/CLI/ArgumentsBuilder.php on line 117

Running on PHP 7.1.9

Thanks

**Comment by sebastianbergmann** [comment]
PHP 7.1 is not supported, you need at least PHP 7.3.
