### ISSUE TITLE
PHP8 support 

### ISSUE THREAD

**Issue by Ilyes512** [sebastianbergmann/phploc#221]
Can we update the php version so it includes php 8? 

Not sure if it is just only an update of composer.json or that it will involve more changes?

**Comment by sebastianbergmann** [comment]
[It is not recommended to use Composer to download and install this tool.](https://github.com/sebastianbergmann/phploc#installation)

**Comment by Ilyes512** [comment]
Any particular reason for that recommendation, besides the possible problems with dependency resolving?
