### ISSUE TITLE
xdebug_disable() call fails with Xdebug 3

### ISSUE THREAD

**Issue by dorianfm** [sebastianbergmann/phploc#222]
`PHP Fatal error:  Uncaught Error: Call to undefined function xdebug_disable() PHPLOC/CLI/Application.php:112`

This is caused because Xdebug 3 no longer has this function, see: https://xdebug.org/docs/upgrade_guide

    xdebug_disable()

    Has been removed.

    To prevent Xdebug from showing stack traces, do not configure Xdebug's develop mode in xdebug.mode, or turn off PHP's html_errors INI setting.

I will attempt a fix and issue a PR.

**Comment by sebastianbergmann** [comment]
This function is not used in current versions of this tool.

**Comment by wblessen** [comment]
Same here, have to remove apt Package phpcpd :-(
