### ISSUE TITLE
Is Average Method Length (LLOC) calculated correctly

### ISSUE THREAD

**Issue by hver** [sebastianbergmann/phploc#68]
I have a question about Average Method Length (LLOC).
In the File phploc/src/Analyser.php at 217-223:
```php
if ($count['classes'] > 0) {
    $count['llocByNoc'] = $count['llocClasses'] / $count['classes'];
}

if ($count['methods'] > 0) {
    $count['llocByNom'] = $count['llocClasses'] / $count['methods'];
}
```
The number of average lines in method (*llocByNom*) is calculated by dividing **number of lines in classes** by **number of methods**.
More correct would be to use the
 **number of lines in methods** devided by **number of methods**
, because in the classes you also have traits, variable, constants, etc. lines.

**Comment by sebastianbergmann** [comment]
Can you please check whether the changes introduced in 082affff3e69fe7bf662ca49189692f6a43cf00d solve this issue? Thanks.

**Comment by hver** [comment]
Yes, now the Average Method LLOC length is correct. Thanks for the fix.
