### ISSUE TITLE
Exclude absolute directory

### ISSUE THREAD

**Issue by joshuaspence** [sebastianbergmann/phploc#79]
Is there any way to exclude a directory using an absolute path? It seems that currently directories can only be excluded with a relative path.

My use case is as follows. Let's say that I have the following directory structure

```
root/
root/a/
root/a/foo/
root/a/bar/
root/b/
root/b/foo/
root/b/bar/
```

What I want to be able to do is run `phploc --exclude=root/a/foo/ root/a/ root/b/`. I believe that in this case, I currently would have to use `phploc --exclude=foo root/a/ root/b/`, which would also exclude `root/b/foo/`, which is unintended.

**Comment by bradjorgensen** [comment]
+1
