### ISSUE TITLE
Fatal error: Class 'SebastianBergmann\PHPLOC\CLI\Application' not found

### ISSUE THREAD

**Issue by Aerendir** [sebastianbergmann/phploc#83]
As in the object, launching phploc i receive the following error:

Fatal error: Class 'SebastianBergmann\PHPLOC\CLI\Application' not found in /Users/Aerendir/Documents/JooServer/_Projects/[xxxxxx]/DevRoot/[xxxxx]/vendor/phploc/phploc/composer/bin/phploc on line 70

As you can see, i use Composer.

Hope someone can help me, thank you!

**Comment by sebastianbergmann** [comment]
I cannot reproduce this.
