### ISSUE TITLE
php warning in Analyser.php

### ISSUE THREAD

**Issue by ChrisPiechowicz** [sebastianbergmann/phploc#85]
Notice: Undefined offset: 11 in /var/www/phpunit/vendor/phploc/phploc/src/Analyser.php on line 414
PHP Notice:  Undefined offset: 11 in /var/www/phpunit/vendor/phploc/phploc/src/Analyser.php on line 419

version 2.0.5

**Comment by sebastianbergmann** [comment]
Do you still run into this issue with the current `master`? Do you have repository that I can test this with?

**Comment by discordier** [comment]
Seems to be working for me so far.
Whenever I run into a repository that has the problem again I will report.
Sadly I do not remember which repository was having the problem back then.

**Comment by sebastianbergmann** [comment]
Please open a new ticket if the issue is still present in phploc 2.1.1. Thanks!
