### ISSUE TITLE
speed up phploc

### ISSUE THREAD

**Issue by thkoch2001** [sebastianbergmann/phploc#92]
I'm trying to run phploc over a repository with 1245 commits and have to restart it monday morning since I don't want to keep my computer running over the weekend.

Some ideas for speed improvements:

- make the metrics to collect selectable
- make the git range configurable
- don't check out every commit but work on the bare repository via a virtual file system
- rewritein Haskell :-) (I'm learning Haskell and there is https://github.com/jhartikainen/hs-language-php - so this might be a nice learning project)

Thank you!

**Comment by sebastianbergmann** [comment]
A pull request for this would be welcome. I will not spend time on this implementing it myself.
