### ISSUE TITLE
 phploc not completely finish

### ISSUE THREAD

**Issue by megapo** [sebastianbergmann/phploc#99]
phploc:
     [exec] phploc 2.0.6 by Sebastian Bergmann.
     [exec] 
     [exec] Directories                                       1047
     [exec] Files                                             6223
     [exec] 
     [exec] Size
     [exec]   Lines of Code (LOC)                          1024150
     [exec]   Comment Lines of Code (CLOC)                   65727 (6.42%)
     [exec]   Non-Comment Lines of Code (NCLOC)             958423 (93.58%)
     [exec]   Logical Lines of Code (LLOC)                  269213 (26.29%)
     [exec]     Classes                                     238901 (88.74%)
     [exec]       Average Class Length                          70
     [exec]       Average Method Length                          6
     [exec]     Functions                                     3301 (1.23%)
     [exec]       Average Function Length                        8
     [exec]     Not in classes or functions                  27011 (10.03%)
     [exec] 
     [exec] Complexity
     [exec]   Cyclomatic Complexity / LLOC                    0.38
     [exec]   Cyclomatic Complexity / Number of Methods       3.45
     [exec] 
     [exec] Dependencies
     [exec]   Global Accesses                                 2852
     [exec]     Global Constants                              2064 (72.37%)
     [exec]     Global Variables                               138 (4.84%)
     [exec]     Super-Global Variables                         650 (22.79%)
     [exec]   Attribute Accesses                             72838
     [exec]     Non-Static                                   68702 (94.32%)
     [exec]     Static                                        4136 (5.68%)
     [exec]   Method Calls                                  181518
     [exec]     Non-Static                                  142968 (78.76%)
     [exec]     Static                                       38550 (21.24%)
     [exec] 
     [exec] Structure
     [exec]   Namespaces                                         0
     [exec]   Interfaces                                        12
     [exec]   Traits                                             0
     [exec]   Classes                                         3374
     [exec]     Abstract Classes                               581 (17.22%)
     [exec]     Concrete Classes                              2793 (82.78%)
     [exec]   Methods                                        35204
     [exec]     Scope
     [exec]       Non-Static Methods                         25922 (73.63%)
     [exec]       Static Methods                              9282 (26.37%)
     [exec]     Visibility
     [exec]       Public Methods                             31524 (89.55%)
     [exec]       Non-Public Methods                          3680 (10.45%)
     [exec]   Functions                                        379
     [exec]     Named Functions                                351 (92.61%)
     [exec]     Anonymous Functions                             28 (7.39%)
     [exec]   Constants                                       7793
     [exec]     Global Constants                               920 (11.81%)
     [exec]     Class Constants                               6873 (88.19%)

spinner while Finished: ABORTED

**Comment by sebastianbergmann** [comment]
Not enough information, closing.
